language: python
python:
    - "2.6"
    - "2.7"
env:
  - DJANGO_VERSION=1.4.1
  - DJANGO_VERSION=1.5.1
install:
  - pip install -r requirements_dev.txt --use-mirrors
  - pip install Django==$DJANGO_VERSION
script:
  - python basitapi/tests/runtests.py
